linux:
	gcc -o classic_pong *.c -O1 -Wall -std=c99 -Wno-missing-braces -I ../include/ -L ../lib/ -lraylib -lGL -lm -lpthread -ldl -lrt -lX11

windows:
	gcc -o classic_pong.exe *.c -O1 -Wall -std=c99 -Wno-missing-braces -I ../include/ -L ../lib/ -lraylib -lopengl32 -lgdi32 -lwinmm